### PR TITLE
general update

### PR DESCRIPTION
**Pull request by elia**
- Use Redis instead of AWS
- update deps
- support for HTTPS
- follow redirects

### CODE REVIEW

**Comment by amicojeko** [comment]
Thanks pal!

**Comment by elia** [comment]
http://jekilizer-redux.herokuapp.com/5

**Comment by amicojeko** [comment]
http://www.jekolize.me/ is back online! :)

btw, by using Redis instead of AWS we loose the persistence of the modified pages!

**Comment by elia** [comment]
Redis is persistent enough I think and Page.load already relied on it to get the page metadata but it's true that you lose a browsable collection of all the generated pages 👨🏻

**Comment by amicojeko** [comment]
I want it to last through months, years, centuries!! :) Redis is not persistent enough! :)


On 04 Nov 2015, at 19:10, Elia Schito <notifications@github.com<mailto:notifications@github.com>> wrote:


Redis is persistent enough I think and Page.load already relied on it to get the page metadata but it's true that you lose a browsable collection of all the generated pages 👨🏻

—
Reply to this email directly or view it on GitHub<https://github.com/amicojeko/jekolizer/pull/2#issuecomment-153812829>.






~~ The information contained in or accompanying this email and any attachment thereto, is intended solely for the use of the stated recipient(s) and may contain information that is confidential and/or privileged. Any dissemination, distribution or copying of this email and any attachment by anyone who is not a stated recipient is strictly prohibited. If you receive this message in error, please notify the sender immediately and delete the message and any attachment from your system without retaining a copy. ~~

**Comment by elia** [comment]
Fair point, also apparently amazon didn't like hotlinking… too bad

**Pull request merged**
